kubeval-chart:
  runs-on: ubuntu-latest
  needs:
    - lint-chart
    - lint-docs
  strategy:
    matrix:
      k8s:
        - v1.19.0
        - v1.20.11
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run kubeval
      env:
        KUBERNETES_VERSION: ${{ matrix.k8s }}
      run: .github/kubeval.sh